
# This file is automatically generated, you probably don't want to edit this

classificationOptions <- if (requireNamespace('jmvcore')) R6::R6Class(
    "classificationOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            dep = NULL,
            indep = NULL,
            testSize = 0.33,
            noOfFolds = 10,
            testing = NULL,
            reporting = NULL,
            classifier = NULL,
            minSplit = 20,
            minBucket = 0,
            complecity = 0.01,
            maxCompete = 4,
            maxSurrogate = 5,
            unsurrogate = 2,
            noCrossValidations = 10,
            maxDepth = 30,
            plotDecisionTree = FALSE, ...) {

            super$initialize(
                package='MachineLearning',
                name='classification',
                requiresData=TRUE,
                ...)

            private$..dep <- jmvcore::OptionVariable$new(
                "dep",
                dep)
            private$..indep <- jmvcore::OptionVariables$new(
                "indep",
                indep)
            private$..testSize <- jmvcore::OptionNumber$new(
                "testSize",
                testSize,
                default=0.33)
            private$..noOfFolds <- jmvcore::OptionNumber$new(
                "noOfFolds",
                noOfFolds,
                default=10)
            private$..testing <- jmvcore::OptionList$new(
                "testing",
                testing,
                options=list(
                    "trainSet",
                    "split",
                    "crossValidation"))
            private$..reporting <- jmvcore::OptionNMXList$new(
                "reporting",
                reporting,
                options=list(
                    "classifMetrices",
                    "confusionMatrix",
                    "AUC"))
            private$..classifier <- jmvcore::OptionList$new(
                "classifier",
                classifier,
                options=list(
                    "simpleDecisionTree",
                    "randomForest"))
            private$..minSplit <- jmvcore::OptionNumber$new(
                "minSplit",
                minSplit,
                default=20)
            private$..minBucket <- jmvcore::OptionNumber$new(
                "minBucket",
                minBucket,
                default=0)
            private$..complecity <- jmvcore::OptionNumber$new(
                "complecity",
                complecity,
                default=0.01)
            private$..maxCompete <- jmvcore::OptionNumber$new(
                "maxCompete",
                maxCompete,
                default=4)
            private$..maxSurrogate <- jmvcore::OptionNumber$new(
                "maxSurrogate",
                maxSurrogate,
                default=5)
            private$..unsurrogate <- jmvcore::OptionNumber$new(
                "unsurrogate",
                unsurrogate,
                default=2)
            private$..noCrossValidations <- jmvcore::OptionNumber$new(
                "noCrossValidations",
                noCrossValidations,
                default=10)
            private$..maxDepth <- jmvcore::OptionNumber$new(
                "maxDepth",
                maxDepth,
                default=30)
            private$..plotDecisionTree <- jmvcore::OptionBool$new(
                "plotDecisionTree",
                plotDecisionTree,
                default=FALSE)

            self$.addOption(private$..dep)
            self$.addOption(private$..indep)
            self$.addOption(private$..testSize)
            self$.addOption(private$..noOfFolds)
            self$.addOption(private$..testing)
            self$.addOption(private$..reporting)
            self$.addOption(private$..classifier)
            self$.addOption(private$..minSplit)
            self$.addOption(private$..minBucket)
            self$.addOption(private$..complecity)
            self$.addOption(private$..maxCompete)
            self$.addOption(private$..maxSurrogate)
            self$.addOption(private$..unsurrogate)
            self$.addOption(private$..noCrossValidations)
            self$.addOption(private$..maxDepth)
            self$.addOption(private$..plotDecisionTree)
        }),
    active = list(
        dep = function() private$..dep$value,
        indep = function() private$..indep$value,
        testSize = function() private$..testSize$value,
        noOfFolds = function() private$..noOfFolds$value,
        testing = function() private$..testing$value,
        reporting = function() private$..reporting$value,
        classifier = function() private$..classifier$value,
        minSplit = function() private$..minSplit$value,
        minBucket = function() private$..minBucket$value,
        complecity = function() private$..complecity$value,
        maxCompete = function() private$..maxCompete$value,
        maxSurrogate = function() private$..maxSurrogate$value,
        unsurrogate = function() private$..unsurrogate$value,
        noCrossValidations = function() private$..noCrossValidations$value,
        maxDepth = function() private$..maxDepth$value,
        plotDecisionTree = function() private$..plotDecisionTree$value),
    private = list(
        ..dep = NA,
        ..indep = NA,
        ..testSize = NA,
        ..noOfFolds = NA,
        ..testing = NA,
        ..reporting = NA,
        ..classifier = NA,
        ..minSplit = NA,
        ..minBucket = NA,
        ..complecity = NA,
        ..maxCompete = NA,
        ..maxSurrogate = NA,
        ..unsurrogate = NA,
        ..noCrossValidations = NA,
        ..maxDepth = NA,
        ..plotDecisionTree = NA)
)

classificationResults <- if (requireNamespace('jmvcore')) R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]],
        confusionMatrix = function() private$.items[["confusionMatrix"]],
        classifMetrices = function() private$.items[["classifMetrices"]],
        classMeasures = function() private$.items[["classMeasures"]],
        decisionTreePlot = function() private$.items[["decisionTreePlot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Decision tree")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title=""))
            self$add(jmvcore::Table$new(
                options=options,
                name="confusionMatrix",
                title="Confusion matrix",
                visible=FALSE,
                rows=0,
                columns=list(
                    list(
                        `name`="class", 
                        `title`="response", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="classifMetrices",
                title="Per class",
                visible=FALSE,
                rows=0,
                columns=list(
                    list(
                        `name`="class", 
                        `title`="class name", 
                        `type`="text"),
                    list(
                        `name`="prec", 
                        `title`="precision", 
                        `type`="number"),
                    list(
                        `name`="rec", 
                        `title`="recall", 
                        `type`="number"),
                    list(
                        `name`="fscore", 
                        `title`="f-score", 
                        `type`="number"),
                    list(
                        `name`="auc", 
                        `title`="AUC", 
                        `type`="number", 
                        `visible`=FALSE))))
            self$add(jmvcore::Table$new(
                options=options,
                name="classMeasures",
                visible=FALSE,
                title="Overall",
                rows=0,
                columns=list(
                    list(
                        `name`="metric", 
                        `title`="Metric", 
                        `type`="text"),
                    list(
                        `name`="value", 
                        `title`="Value", 
                        `type`="number"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="decisionTreePlot",
                title="Decision tree plot",
                visible=FALSE,
                width=400,
                height=300,
                renderFun=".plot"))}))

classificationBase <- if (requireNamespace('jmvcore')) R6::R6Class(
    "classificationBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'MachineLearning',
                name = 'classification',
                version = c(1,0,0),
                options = options,
                results = classificationResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE)
        }))

#' Decision tree
#'
#' 
#' @param data .
#' @param dep .
#' @param indep .
#' @param testSize .
#' @param noOfFolds .
#' @param testing .
#' @param reporting .
#' @param classifier .
#' @param minSplit .
#' @param minBucket .
#' @param complecity .
#' @param maxCompete .
#' @param maxSurrogate .
#' @param unsurrogate .
#' @param noCrossValidations .
#' @param maxDepth .
#' @param plotDecisionTree .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$confusionMatrix} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$classifMetrices} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$classMeasures} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$decisionTreePlot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$confusionMatrix$asDF}
#'
#' \code{as.data.frame(results$confusionMatrix)}
#'
#' @export
classification <- function(
    data,
    dep,
    indep,
    testSize = 0.33,
    noOfFolds = 10,
    testing,
    reporting,
    classifier,
    minSplit = 20,
    minBucket = 0,
    complecity = 0.01,
    maxCompete = 4,
    maxSurrogate = 5,
    unsurrogate = 2,
    noCrossValidations = 10,
    maxDepth = 30,
    plotDecisionTree = FALSE) {

    if ( ! requireNamespace('jmvcore'))
        stop('classification requires jmvcore to be installed (restart may be required)')

    if ( ! missing(dep)) dep <- jmvcore::resolveQuo(jmvcore::enquo(dep))
    if ( ! missing(indep)) indep <- jmvcore::resolveQuo(jmvcore::enquo(indep))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(dep), dep, NULL),
            `if`( ! missing(indep), indep, NULL))


    options <- classificationOptions$new(
        dep = dep,
        indep = indep,
        testSize = testSize,
        noOfFolds = noOfFolds,
        testing = testing,
        reporting = reporting,
        classifier = classifier,
        minSplit = minSplit,
        minBucket = minBucket,
        complecity = complecity,
        maxCompete = maxCompete,
        maxSurrogate = maxSurrogate,
        unsurrogate = unsurrogate,
        noCrossValidations = noCrossValidations,
        maxDepth = maxDepth,
        plotDecisionTree = plotDecisionTree)

    analysis <- classificationClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
